name: RandomGamingOrigins
version: '${project.version}'
main: me.randomgamingdev.randomgamingorigins.RandomGamingOrigins
api-version: 1.18
authors: [ RandomGamingDev ]
description: An origins plugin created by me, RandomGamingDev!

commands:
  ping:
    usage: /<command>
    permission: randomgamingorigins.ping
  originsgui:
    usage: /<command> [<player>]
    permission: randomgamingorigins.originsguicommand
  origins:
    usage: /<command> [<player>]
    permission: randomgamingorigins.originscommand
  getorigin:
    usage: /<command> [<player>]
    permission: randomgamingorigins.getorigincommand
  originssave:
    usage: /<command> [<string>]
    permission: randomgamingorigins.save
  originsload:
    usage: /<command> [<string>]
    permission: randomgamingorigins.load
  weeklyorb:
    usage: /<command>
    permission: randomgamingorigins.weeklyorb
  getpouch:
    usage: /<command> [<player>]
    permission: randomgamingorigins.getpouch
  setorigin:
    usage: /<command> [<player>] [<origin id>]
    permission: randomgamingorigins.setorigin
  ability:
    usage: /<command> [<ability>]
